### ISSUE TITLE
AMDGPU missing in PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by yshui** [Ashark/archlinux-amdgpu-pro#37]
Several libraries (libdrm, etc) is installed into /opt/amdgpu-pro, but that's not in PKG_CONFIG_PATH, so things will refuse to compile.

Better add it to PKG_CONFIG_PATH.

**Comment by brainpower** [comment]
Can you check if my fix-37 branch [1] fixes your compile issues? (You may have to re-login.)

[1] https://github.com/brainpower/archlinux-amdgpu/tree/fix-37

**Comment by yshui** [comment]
The problem is kind of complicated. So if you want to compile lib32-* which depends on libdrm, you would need /opt/amdgpu-pro/lib/i386-*/pkgconfig in the PKG_CONFIG_PATH. But normally PKGBUILDs would only include '/usr/lib32/pkgconfig'

Can we just install amdgpu-pro-libdrm into /usr/lib and /usr/lib32? It conflict with system libdrm anyway.

**Comment by brainpower** [comment]
I'll look into installing or symlinking the pc files into `/usr/lib{,32/pkgconfig/`, but that will take some time.
Those *.pc files have hardcoded paths to /opt/amdgpu inside, so it should suffice to move only those to /usr .
I don't want to move the actual *.so's, because some *.so's have (or at least had at some point) hardcoded paths to other *.so's inside and then many things will probably break.

**Comment by yshui** [comment]
@brainpower I see. That makes sense

**Comment by Ashark** [comment]
Stale
