### ISSUE TITLE
move_libdir function in PKGBUILD

### ISSUE THREAD

**Issue by Ashark** [Ashark/archlinux-amdgpu-pro#62]
by @gardotd426 in AUR comment:
I'm confused about move_libdir in the PKGBUILD.
It doesn't work at all. Packages still got built with files in /usr/lib/x86_64-linux-gnu, /usr/lib32/i686-linux-gnu, etc. Nothing gets moved anywhere, so that little snippet does nothing.
amdgpu-pro-libgl (20.30_1109583-1) is one example. The resulting Arch package has amdgpu_dri.so in /usr/lib/x86_64-linux-gnu/dri/

**Comment by Ashark** [comment]
This function was used in PKGBUILD until 19.20_812932-1, where I heavily reworked this project. See [history](https://aur.archlinux.org/cgit/aur.git/log/?h=amdgpu-pro-installer). I have made it like in debian, but previously, some libraries were moved to the "normal" system path.
Probably, it could be used for vulkan-amdgpu-pro, to remove dependency on a amdgpu-pro-meta, but I am not sure if it could be done. Probably, there could be hardcoded pathes in libraries and so on.
So, it is needed to make additional investigation about usage of this function.

**Comment by gardotd426** [comment]
Yeah that's understandable.

vulkan-amdgpu-pro needs to be kept in /opt/ because for one, that's where the .json files point, but more importantly, putting amdvlk64.so into /usr/lib/ would make it conflict with AMDVLK, which goes against the whole purpose of making these packages be able to live side by side. So vulkan-amdgpu-pro should stay where it is as far as the installed files, I think. 

But just an FYI, vulkan-amdgpu-pro definitely doesn't depend on pro-core-meta or core-meta at all. The only files inside either of those packages are:

`amdgpu-pro-core-meta /usr/share/licenses/amdgpu-pro-core-meta/copyright`
and
`amdgpu-core-meta /usr/share/licenses/amdgpu-core-meta/copyright`

They contain nothing else. So you can remove that dependency for vulkan-amdgpu-pro and lib32-vulkan-amdgpu-pro.

**Comment by Ashark** [comment]
I am using move_libdir function in 20.45_1188099-5
